from standard_normal_probability_2 import *
print(calc_standard_normal_probability(0, 1, 100, "left endpoint"))
print()
print(calc_standard_normal_probability(0, 1, 100, "right endpoint"))
print()
print(calc_standard_normal_probability(0, 1, 100, "midpoint"))
print()
print(calc_standard_normal_probability(0, 1, 100, "trapezoidal"))
print()
print(calc_standard_normal_probability(0, 1, 100, "simpson"))
print()